# Image
FROM node:10
  
# Set up app directory
ARG WORK_DIR
WORKDIR $WORK_DIR

# copy package files
COPY package.json ./
COPY yarn.lock ./

# install modules
RUN yarn

# run application
EXPOSE 80
CMD ["yarn", "dev"]