# Image
FROM node:10

# Environment variables
ENV PORT=80

# Set up app directory
ARG WORK_DIR
WORKDIR $WORK_DIR

# copy package files
COPY package*.json ./

# install modules
RUN npm install

# run application
EXPOSE 80 443 9229
CMD ["npm", "run", "dev"]