# Image
FROM node:10

# Environment variables
ENV PORT=80

# Set up app directory
ARG WORK_DIR
WORKDIR $WORK_DIR

# copy package files
COPY package.json yarn.lock ./

# install modules
RUN yarn

# run application
EXPOSE 80 9229
CMD ["yarn", "run", "dev"]