# Build Image
FROM node:11.6-alpine AS base

# Dev environment arguments
ARG WORK_DIR

# RUN npm i yarn -g

# copy package files
COPY package.json ./
COPY yarn.lock ./

# install modules
RUN yarn

COPY . ./

# Build project
RUN yarn build

# Production Image
FROM nginx

# Copy needed files
COPY nginx.config /etc/nginx/conf.d/default.conf
COPY --from=base build /usr/share/nginx/html
